URL=https://dl.rockylinux.org/pub/rocky/10/images/x86_64/Rocky-10-GenericCloud-Base.latest.x86_64.qcow2
SOURCE=source-rocky10.img
OSVARIANT=rocky10
#OSVARIANT=rocky-unknown
CONSOLE="pty,target_type=virtio"
